USE health;

-- Put your bcrypt hash here (generated by: node make_hash.js smiths)
INSERT INTO users (username, password_hash)
VALUES ('gold', '$2b$10$LwpDvqqaS1F6aHMZ.BVy6e7y3KMfjHtWWcbefn.sPHiY7B6pTIO7C');

INSERT INTO workouts (user_id, workout_date, type, duration_mins, notes)
VALUES
((SELECT id FROM users WHERE username='gold'), '2025-12-01', 'Run', 30, 'Easy run'),
((SELECT id FROM users WHERE username='gold'), '2025-12-03', 'Weights', 45, 'Upper body'),
((SELECT id FROM users WHERE username='gold'), '2025-12-05', 'Yoga', 25, 'Stretch');
